language: scala
scala:
  - 2.11.5
jdk:
  - oraclejdk8

before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database sorm_test;'
install: 
  mvn install -DskipTests=true -Dgpg.skip=true
script:
  mvn test
